application: gocitybus2
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /simple
  script: home.application

- url: /api
  script: api.application

- url: /google_transit/*
  static_files: /google_transit/\1
  upload: /google_transit/*.txt

- url: /images
  static_dir: images

- url: /.*
  static_files: index.html
  upload: index.html

